name: Dev-CI
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Move files to deploy
        run: |
          mkdir deploy
          cp index.html deploy/index.html
          cp script.js deploy/script.js
          cp style.css deploy/style.css
      
      - name: Cloud Storage Uploader
        uses: google-github-actions/upload-cloud-storage@v0.2.0
        with:
          entrypoint: deploy
          credentials: ${{secrets.GCP_BUCKET_SECRET}}
          # The path to a file or folder inside the action's filesystem that should be uploaded to the bucket. You can specify either the absolute path or the relative path from the action.
          path: .
          # GCS bucket name of form <bucketname> or with an optional prefix of form <bucketname>/<prefix>
          destination: git-basics-hosting/dev
